---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database
  namespace: default
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgAsTOaMYaXf9VM81XLuz9jh+FkSTTFTUyxLqUnIdh1YeSwBQb/Oc15h8iPXLPksa3s+Gw2u/jPKfBWBASB+nSq24QJLO56HN5+YAQKym7RXI4d0f1IFeOapFZCvTGx1Rb6dMVhFI8bTScHjYuMx4jcUmGM1F8KaeY6jXOWaerYoCLo2RWoMlQwGffHgeGBju6mPt2LPSt7gcA0FVYFtRCx++TVUR5EOB04DVD3FQ/ANL8uTgz9QInPB4AEobdtwZvGEz9w0BTDFxAhQkiV/BB76LP++9dMgvaplxBUnqi2ClPS5cEHBAsKELp7xaVUvv1h2MNbTW3gqKdJBKC8div6pMgN9eT0AR7dI/rN4n1BQFSmCVeSvjKc5u8+Gty7+rn9zDHDu4zMcFTR0v7hHIlPdm5+WrWPGJZkveEQ9wBwbuF9mJGgdMAbjZI7befkSNrLn4JhwpmS9QqRwjBnsD7pDN9HFA++xFNXU5wn1Ao44miX9wGcVTinw5Mq25KvuTLT4OxEm7DBp2O+m/1ryMOfRoi9fIhNVoe/BykUdF5pWZGR53ZIBmK1CkdxqRJjYkiG4bWwh05+s2uEBV4HGZ9y6t+NNI17x6HUePqhklwgSgEqQ4/+ljE/J1FbAd3DgecDTFQvEuASP/r1gD/07WeEWVKOaQIz5XquygQQuSzKRSMnlDpyOfmNpeooNWVZ32MXiyfhrDqTuFCz89H8T2qEwPg==
    SECRET_KEY: AgBvZo2eVwQKW0EOwBUHxVtyiQY6EoHWzg63yx9FsbgnjwjeoPjWuTAf9hsvc2m6DLQxsXR7PqWGB+Wz+kc/iMiEX7azy6zy3PzhJIu1/AaKm0X63RoNeZqGGMEVo5bwhvJkp/bpP9J15Ii73OXmSknUHSzF2ilnF2jYduLIyctRnpmz5BKs0pDS9+5dsNbTOGvOs37+1KEIWthyt7gdiNWyiM77pIY5lonFls933qNWWvfrlNLXTzGmEHRA3v788wvacx9UKUUQUFaNlloq5FcpT/sn2qScnvV5L02paXzpFkl7fdO2UM2uxqhdCIxC1EWreqH1lbSzYDAkhth6LO3yx0nv9BTmAhFiI/zcsVJxsE5ny8ivqLUeo/TXZHyRNCI0pZYQU0JFL8V6jiV7U5MKvLyiPDTX2X8q0nH4dYbksH510RM2pwEikl5DdZOSJAZAEBfLwA9E7aRlcILCYNKwr9CcOHjE78HAwwYAic2i1JJW2aT/Q1ugRJBPG1ALvXSG1RChPi7tNIgdLb3nIQbWe9WfdHDTVVzZQqM8iSZKvy2yqLZUeTwRNYd1wQox+JtDbkguBwtiQ+D7GY1HRhm+w5xsZn7ysW9XOEPL2yqL5eRiVhTYrFnOrVEqqH4XBmgixXWRCGFYre2yf2Y/35Xx/tyv3vHXRqTQzjWq8pBh1/clzMmLuW+MX9TQE16fn+UJlagaE+oyLi4vEep6nLnh8w8bAlTalxdwEP6rLfbbkY627Iu405cLpf9m067k4/NFeA==
  template:
    metadata:
      creationTimestamp: null
      name: database
      namespace: default
